- hosts: all
  tasks:
    - name: Build spark master using mvn with hadoop 2.7
      shell:
        cmd: |
          set -ex
          sudo apt-get update -y

          # Install java
          sudo apt-get install default-jre -y
          sudo apt-get install default-jdk -y
          java_home=$(dirname $(dirname $(update-alternatives --list javac)))
          echo "export JAVA_HOME=${java_home}" >> ~/.profile
          echo "export PATH=${java_home}/bin:$PATH" >> ~/.profile
          source ~/.profile

          # Install maven
          wget http://www.us.apache.org/dist/maven/maven-3/3.6.1/binaries/apache-maven-3.6.1-bin.tar.gz
          tar -xvf apache-maven-3.6.1-bin.tar.gz
          export PATH=$PWD/apache-maven-3.6.1/bin:$PATH
  
          # Install vim
          sudo apt-get install vim -y

          # fix error: java.net.UnknownHostException: ubuntu: ubuntu: Name or service not known
          sudo sed -i -e '/127.0.0.1/ s/\(localhost\)/'$(hostname)' \1/' /etc/hosts

          cd {{ ansible_user_dir }}/{{ zuul.project.src_dir }}
          
          ./build/mvn clean install -DskipTests -Paarch64 -Phadoop-2.7 -Pyarn -Phive -Phive-thriftserver -Pkinesis-asl -Pmesos
          ./build/mvn test -Paarch64 -Phadoop-2.7 -Pyarn -Phive -Phive-thriftserver -Pkinesis-asl -Pmesos -fn -pl !core/sql

        chdir: '/home/zuul/src'
        executable: /bin/bash
      environment: '{{ global_env }}'